name = "backend"
main = "src/index.ts"
compatibility_date = "2024-12-25"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
MY_VAR = "my-variable"
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMzY1ZTFhYWQtOGU1NS00ZWIxLWJmNjQtMzRkNzE3OWI2MzMxIiwidGVuYW50X2lkIjoiNTQ5ODRjZjYzZjEwNzU3YWFhNWM5NTk4NzYyZDdhODZmZDIzMjMxMTc4ZDRkZmM0OTY3NThiMTdkMDQ3OTVlNSIsImludGVybmFsX3NlY3JldCI6IjExMzg1ZGU1LWVkYWMtNDRmZS05MzhkLTA3OTY2OWZhNDBiYyJ9.ZuysrIvkQOj4F26IqsL-ABHedTiXDcUeyAI2lLCOnlQ"
JWT_SECRET='secret-key'
